### ISSUE TITLE
Health Check URL used isn't accurate

### ISSUE THREAD

**Issue by Enuratique** [IvoNet/docker-nordvpn#1]
Using the nordvpn-privoxy Docker image to host a proxy backed by my NordVPN account. Looked at the health of the container running it and docker ps says it is unhealthy. I inspect the container and see the health check URL is https://api.nordvpn.com/vpn/check/full ... I've confirmed by exec -it bash 'ing into the running container that both OpenVPN and privoxy are running. When I run the curl command used in the healthcheck declaration in the Dockerfile for nordvpn, I get the following result:

`{"ip":"87.249.138.142","isp":"TTNET s.r.o.","status":"Unprotected","country":"Czechia","code":"CZ"}`

Because it says unprotected, the health check fails. This IP is not a Czechoslovakian IP, it's a US based in New York IP.

https://nordvpn.com/wp-admin/admin-ajax.php?action=get_user_info_data is a more accurate URL to use for the healthcheck curl, but it does not report a status of protected or unprotected unfortunately.

I discovered this issue when Googling found this discussion:

https://gist.github.com/Dreyer/161b920f0d8300ed3bc750ae2f80c339

**Comment by IvoNet** [comment]
Agreed but I do not have time to fix it right now. Are you capable of fixing it and making a Pull Request? I will certainly give credit where credit is due.
